backend:
  name: git-gateway
  branch: main  # 你的 Git 主分支名
media_folder: "static/img/uploads"  # 上传图片的存储路径
public_folder: "/img/uploads"      # 图片在前端的访问路径
collections:
  - name: "posts"   # 内容集合名称（如文章）
    label: "文章"
    folder: "content/posts"  # Markdown 文件的存储路径
    create: true
    fields:
      - { name: "title", label: "标题", widget: "string" }
      - { name: "date", label: "日期", widget: "datetime" }
      - { name: "tags", label: "标签", widget: "list" }
      - { name: "body", label: "正文", widget: "markdown" }